Finished all-in-one app script
Pandora-IsoMemo/all-in-one-apps pull request #3
Opened 2024-01-24 09:26 UTC by jan-abel-inwt

2024-01-29 14:24 UTC, arunge requested changes
The script will be very helpful! I have nothing to add, the choices are very clear.

We could only make the documentation a bit clearer, please see my notes!

2024-01-29 14:24 UTC, arunge commented on README.md
> +
We could add a screenshot:
![image](https://github.com/Pandora-IsoMemo/all-in-one-apps/assets/16759098/1278ef98-10a0-49e8-ab8f-f986f25c4aee)

but maybe first update the title?

2024-01-29 14:28 UTC, arunge commented on README.md
> +docker & netstat
And for now, we must add that this is only working for Linux!!

2024-01-31 07:55 UTC, jan-abel-inwt commented
I updated the readme and changed the menu title. Have a look

2024-02-01 08:11 UTC, arunge approved these changes
only a tiny remark below

2024-02-01 08:11 UTC, arunge commented on README.md
> +**NO SOLUTION FOR WINDOWS**
```suggestion
**CURRENTLY NO SOLUTION FOR WINDOWS**
```

2024-02-01 10:09 UTC, merged